language: node_js
node_js:
  - "7"
script:
  - newman run api/Conduit.postman_collection.json -e api/Conduit.postman_integration_test_environment.json --global-var "EMAIL=$CONDUIT_EMAIL" --global-var "PASSWORD=$CONDUIT_PASSWORD"
